backend:
  name: git-gateway
  branch: main  # Altere "master" para a branch principal do seu repositório, se necessário.

media_folder: "uploads"
public_folder: "/uploads"
 

collections:
  - name: "pages"
    label: "Páginas"
    files:
      - label: "Página Inicial"
        name: "home"
        file: "content/home.md"  # Caminho onde o conteúdo da página será salvo.
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Conteúdo", name: "body", widget: "markdown" }
